language: csharp

os:
  - osx

# Ubuntu 14.04
sudo: required
dist: trusty

# OS X 10.12
osx_image: xcode9.2

mono:
  - 4.4.2

dotnet: 2.1.4
  
script:
  - ./build.sh --verbosity diagnostic

cache:

  directories:
  - .cake/tools